#!/bin/sh
# Build the device payload blob + manifest header + the stager binary.
set -e
P=${1:-$HOME/jidu6801/payload}
OUT=${2:-$HOME/jidu6801/autostart/out}
mkdir -p "$OUT"
IMG=$P/Image; INITRD=$P/part1.bin; DTB=$P/handoff.dtb
for f in "$IMG" "$DTB"; do [ -f "$f" ] || { echo "missing $f"; exit 1; }; done
if [ -f "$INITRD" ]; then WITH_INITRD=1; else WITH_INITRD=0; INITRD=/dev/null; echo "(no initrd: squashfs-root payload)"; fi

cat "$IMG" $([ "$WITH_INITRD" = 1 ] && echo "$INITRD") "$DTB" > "$OUT/payload.bin"

python3 - "$IMG" "$INITRD" "$DTB" "$OUT/payload_meta.h" <<'PY'
import os, sys, zlib
img, initrd, dtb, hdr = sys.argv[1:5]
def info(p):
    d = open(p, 'rb').read()
    return len(d), zlib.crc32(d) & 0xffffffff
il, ic = info(img); rl, rc = ((info(initrd) if os.path.exists(initrd) else (0,0))); dl, dc = info(dtb)
with open(hdr, 'w') as f:
    f.write("/* generated by build.sh - do not edit */\n")
    f.write("#define PL_IMAGE_OFF   0x0UL\n#define PL_IMAGE_LEN   %d\n#define PL_IMAGE_CRC   0x%08xu\n" % (il, ic))
    f.write("#define PL_INITRD_OFF  0x%xUL\n#define PL_INITRD_LEN  %d\n#define PL_INITRD_CRC  0x%08xu\n" % (il, rl, rc))
    f.write("#define PL_DTB_OFF     0x%xUL\n#define PL_DTB_LEN     %d\n#define PL_DTB_CRC     0x%08xu\n" % (il+rl, dl, dc))
print("sizes: image %d, initrd %d, dtb %d" % (il, rl, dl))
print("crcs : image %08x, initrd %08x, dtb %08x" % (ic, rc, dc))
PY
cp "$OUT/payload_meta.h" ./payload_meta.h
aarch64-linux-gnu-gcc -O2 -static -Wall -o "$OUT/jidu6801_stage" jidu6801_stage.c
echo "payload.bin: $(stat -c %s "$OUT/payload.bin") bytes; stager: $(stat -c %s "$OUT/jidu6801_stage") bytes"
