// jidu6801_stage - device-side handoff stager (runs on STOCK linux, no host needed).
//
//  --verify              : check the payload volume against the compiled-in manifest
//  --dry                 : read the module's staging base and print the layout, no writes
//  --stage               : patch the DTB's initrd pointers, stream Image+initrd+DTB into
//                          the module-owned staging RAM via /dev/mem, read the whole run
//                          back and verify it, then print the FIRE command.
//
// Every failure path prints why and exits non-zero; the caller boots stock in that case.
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/sysmacros.h>

#include "payload_meta.h"      /* generated by build.sh from the real payload */

#define A2M 0x200000UL
#define SECTOR 65536

static uint32_t crc32_buf(uint32_t crc, const void *p, size_t n)
{
	const unsigned char *b = p;
	while (n--) { crc ^= *b++; for (int i = 0; i < 8; i++) crc = (crc >> 1) ^ (0xEDB88320u & -(crc & 1)); }
	return crc;
}
static uint32_t crc32_fd(int fd, unsigned long off, size_t len, uint32_t *out_len_ok)
{
	static unsigned char buf[SECTOR];
	uint32_t crc = 0xffffffff; size_t got = 0;
	while (got < len) {
		size_t want = len - got > SECTOR ? SECTOR : len - got;
		ssize_t n = pread(fd, buf, want, off + got);
		if (n <= 0) { if (out_len_ok) *out_len_ok = 0; return crc; }
		crc = crc32_buf(crc, buf, n); got += n;
	}
	if (out_len_ok) *out_len_ok = 1;
	return ~crc;
}

/* --- find the ubi payload volume's char device --- */
static int open_payload(void)
{
	int fd = open("/dev/ubi1_0", O_RDONLY);
	if (fd >= 0) return fd;
	/* node may not exist: build it from sysfs */
	FILE *f = fopen("/sys/class/ubi/ubi1_0/dev", "r");
	if (!f) { fprintf(stderr, "no /sys/class/ubi/ubi1_0/dev - volume missing?\n"); return -1; }
	unsigned maj, min;
	if (fscanf(f, "%u:%u", &maj, &min) != 2) { fclose(f); return -1; }
	fclose(f);
	unlink("/dev/ubi1_0");
	if (mknod("/dev/ubi1_0", S_IFCHR | 0600, makedev(maj, min)) < 0 && errno != EEXIST) {
		perror("mknod /dev/ubi1_0"); return -1;
	}
	return open("/dev/ubi1_0", O_RDONLY);
}

/* --- module-reported staging window --- */
static int read_run(unsigned long *pa, unsigned long *size)
{
	FILE *f = fopen("/proc/jidu6801_stage", "r");
	char line[128]; int got = 0;
	if (!f) { perror("open /proc/jidu6801_stage"); return -1; }
	while (fgets(line, sizeof line, f)) {
		if (sscanf(line, "run_phys : 0x%lx", pa) == 1) got |= 1;
		if (sscanf(line, "run_size : 0x%lx", size) == 1) got |= 2;
	}
	fclose(f);
	if (got != 3) { fprintf(stderr, "could not parse staging base from /proc/jidu6801_stage\n"); return -1; }
	return 0;
}

/* --- FDT: patch /chosen/linux,initrd-{start,end} in place (big-endian u64) --- */
static uint32_t be32(const unsigned char *p) { return (p[0]<<24)|(p[1]<<16)|(p[2]<<8)|p[3]; }
static int fdt_patch_initrd(unsigned char *fdt, size_t len, uint64_t start, uint64_t end)
{
	if (len < 40 || be32(fdt) != 0xd00dfeed) { fprintf(stderr, "not an FDT\n"); return -1; }
	uint32_t off_struct = be32(fdt+8), off_strings = be32(fdt+12), tot = be32(fdt+4);
	if (tot > len) { fprintf(stderr, "fdt totalsize %u > %zu\n", tot, len); return -1; }
	unsigned char *p = fdt + off_struct, *endp = fdt + off_struct + be32(fdt+36);
	/* The root node is itself a BEGIN_NODE, so depth counts nodes we are inside:
	 * root -> 1, /chosen -> 2.  Track chosen by remembering its depth. */
	int depth = 0, chosen_depth = -1, want_start = 0, want_end = 0;
	while (p + 4 <= endp) {
		uint32_t tag = be32(p); p += 4;
		if (tag == 1) {                       /* BEGIN_NODE */
			const char *name = (const char *)p;
			p += strlen(name) + 1; p = (unsigned char *)(((uintptr_t)p + 3) & ~3UL);
			depth++;
			if (depth == 2 && !strcmp(name, "chosen")) chosen_depth = depth;
		} else if (tag == 2) {                /* END_NODE */
			if (chosen_depth > 0 && depth == chosen_depth) chosen_depth = -1;
			depth--;
		} else if (tag == 3) {                /* PROP */
			uint32_t plen = be32(p), noff = be32(p+4); p += 8;
			const char *pname = (const char *)(fdt + off_strings + noff);
			if (chosen_depth > 0 &&
			    (!strcmp(pname, "linux,initrd-start") || !strcmp(pname, "linux,initrd-end"))) {
				if (plen != 8) { fprintf(stderr, "%s is %u bytes (need 8)\n", pname, plen); return -1; }
				uint64_t v = !strcmp(pname, "linux,initrd-start") ? start : end;
				for (int i = 0; i < 8; i++) p[7-i] = (v >> (8*i)) & 0xff;
				if (!strcmp(pname, "linux,initrd-start")) want_start = 1; else want_end = 1;
			}
			p += (plen + 3) & ~3UL;
		} else if (tag == 4) { /* NOP */ }
		else if (tag == 9) break;
		else { fprintf(stderr, "bad fdt tag %u\n", tag); return -1; }
	}
	if (!want_start || !want_end) {
		if (PL_INITRD_LEN) { fprintf(stderr, "initrd properties not found in /chosen\n"); return -1; }
		return 0;                      /* squashfs boot: nothing to patch */
	}
	return 0;
}

static unsigned char *map_phys(unsigned long pa, size_t len)
{
	int fd = open("/dev/mem", O_RDWR);
	if (fd < 0) { perror("open /dev/mem"); return NULL; }
	size_t page = pa & ~4095UL, delta = pa & 4095;
	void *m = mmap(NULL, delta + len, PROT_READ | PROT_WRITE, MAP_SHARED, fd, page);
	close(fd);
	if (m == MAP_FAILED) { perror("mmap /dev/mem"); return NULL; }
	return (unsigned char *)m + delta;
}
static void unmap_phys(unsigned char *p, unsigned long pa, size_t len)
{
	size_t page = pa & ~4095UL, delta = pa & 4095;
	munmap(p - delta, delta + len);
}

int main(int argc, char **argv)
{
	const char *mode = argc > 1 ? argv[1] : "";
	unsigned long run_pa = 0, run_size = 0;
	int fd = open_payload();
	if (fd < 0) return 1;

	unsigned long img_len = PL_IMAGE_LEN, initrd_len = PL_INITRD_LEN, dtb_len = PL_DTB_LEN;
	unsigned long image_pa, initrd_pa, dtb_pa, flush_len;

	if (!strcmp(mode, "--verify")) {
		uint32_t ok1, ok2, ok3;
		uint32_t c1 = crc32_fd(fd, PL_IMAGE_OFF, img_len, &ok1);
		uint32_t c2 = crc32_fd(fd, PL_INITRD_OFF, initrd_len, &ok2);
		uint32_t c3 = crc32_fd(fd, PL_DTB_OFF, dtb_len, &ok3);
		printf("payload: image crc=%08x want=%08x %s\n", c1, PL_IMAGE_CRC, c1 == PL_IMAGE_CRC ? "OK" : "BAD");
		printf("payload: initrd crc=%08x want=%08x %s\n", c2, PL_INITRD_CRC, c2 == PL_INITRD_CRC ? "OK" : "BAD");
		printf("payload: dtb    crc=%08x want=%08x %s\n", c3, PL_DTB_CRC, c3 == PL_DTB_CRC ? "OK" : "BAD");
		close(fd);
		return (ok1 && ok2 && ok3 && c1 == PL_IMAGE_CRC && c2 == PL_INITRD_CRC && c3 == PL_DTB_CRC) ? 0 : 1;
	}

	if (read_run(&run_pa, &run_size) < 0) { close(fd); return 1; }
	image_pa  = run_pa;
	initrd_pa = run_pa;                       /* unused when there is no ramdisk */
	if (initrd_len) {
		initrd_pa = (image_pa + img_len + A2M - 1) & ~(A2M - 1);
		dtb_pa    = (initrd_pa + initrd_len + A2M - 1) & ~(A2M - 1);
	} else {
		dtb_pa    = (image_pa + img_len + A2M - 1) & ~(A2M - 1);
	}
	flush_len = dtb_pa + dtb_len - image_pa;
	if (flush_len > run_size) { fprintf(stderr, "payload overflows staging\n"); close(fd); return 1; }

	printf("run_pa=0x%lx run_size=0x%lx\n", run_pa, run_size);
	printf("image=0x%lx initrd=0x%lx dtb=0x%lx flush_len=0x%lx\n",
	       image_pa, initrd_pa, dtb_pa, flush_len);
	if (!strcmp(mode, "--dry")) { close(fd); return 0; }

	/* 1. read the DTB template, patch the initrd pointers */
	unsigned char *dtb = malloc(dtb_len);
	if (!dtb) return 1;
	if (pread(fd, dtb, dtb_len, PL_DTB_OFF) != (ssize_t)dtb_len) { fprintf(stderr, "dtb read\n"); return 1; }
	if (PL_INITRD_LEN) {
		if (fdt_patch_initrd(dtb, dtb_len, initrd_pa, initrd_pa + initrd_len) < 0) return 1;
		printf("dtb: initrd-start=0x%lx end=0x%lx patched\n", initrd_pa, initrd_pa + initrd_len);
	} else {
		printf("dtb: no ramdisk (squashfs-root payload)\n");
	}

	/* 2. stream Image and initrd into staging RAM.  Each part carries its own
	 * expected crc: with no ramdisk the DTB lands in slot 1, so an index-based
	 * mapping would check it against the (absent) initrd's crc. */
	uint32_t dtb_crc = ~crc32_buf(0xffffffff, dtb, dtb_len);
	struct { unsigned long off, pa, len; const char *name; unsigned char *pre; uint32_t crc; } parts[3] = {
		{ PL_IMAGE_OFF,  image_pa,  img_len,  "Image",  NULL, PL_IMAGE_CRC },
		{ PL_INITRD_OFF, initrd_pa, initrd_len, "initrd", NULL, PL_INITRD_CRC },
		{ PL_DTB_OFF,    dtb_pa,    dtb_len,  "dtb",    dtb,  dtb_crc },
	};
	static unsigned char buf[SECTOR];
	int nparts = initrd_len ? 3 : 2;
	if (!initrd_len) { parts[1] = parts[2]; }        /* Image, dtb only */
	for (int i = 0; i < nparts; i++) {
		unsigned char *dst = map_phys(parts[i].pa, parts[i].len);
		if (!dst) return 1;
		size_t done = 0; uint32_t crc = 0xffffffff;
		while (done < parts[i].len) {
			size_t want = parts[i].len - done > SECTOR ? SECTOR : parts[i].len - done;
			ssize_t n;
			if (parts[i].pre) { memcpy(buf, parts[i].pre + done, want); n = want; }
			else if ((n = pread(fd, buf, want, parts[i].off + done)) <= 0) { fprintf(stderr, "%s read at %zu\n", parts[i].name, done); return 1; }
			memcpy(dst + done, buf, n);
			crc = crc32_buf(crc, buf, n);
			done += n;
		}
		printf("staged %-6s 0x%lx+0x%lx crc=%08x\n", parts[i].name, parts[i].pa, parts[i].len, ~crc);
		unmap_phys(dst, parts[i].pa, parts[i].len);
	}

	/* 3. read the whole staging run back and verify: each part matches its
	 * source (the DTB against the *patched* image we wrote, since its bytes
	 * depend on this boot's staging base), and every gap is zero. */
	unsigned char *run = map_phys(run_pa, run_size);
	if (!run) return 1;
	int bad = 0;
	for (int i = 0; i < nparts && !bad; i++) {
		uint32_t crc = ~crc32_buf(0xffffffff, run + (parts[i].pa - run_pa), parts[i].len);
		if (crc != parts[i].crc) {
			fprintf(stderr, "verify %s: got %08x want %08x\n", parts[i].name, crc, parts[i].crc);
			bad = 1;
		}
	}
	/* gaps between (and around) the three parts must be zero, byte-exact */
	{
		unsigned long bounds[4][2]; int nb = 0;
		unsigned long prev = 0;
		for (int i = 0; i < nparts; i++) {
			unsigned long s = parts[i].pa - run_pa;
			if (s > prev) { bounds[nb][0] = prev; bounds[nb][1] = s; nb++; }
			prev = s + parts[i].len;
		}
		if (prev < run_size) { bounds[nb][0] = prev; bounds[nb][1] = run_size; nb++; }
		for (int g = 0; g < nb && !bad; g++) {
			for (unsigned long o = bounds[g][0]; o < bounds[g][1] && !bad; o += SECTOR) {
				size_t n = bounds[g][1] - o > SECTOR ? SECTOR : bounds[g][1] - o;
				for (size_t k = 0; k < n; k++)
					if (run[o + k]) { fprintf(stderr, "staging not zero at 0x%lx\n", run_pa + o + k); bad = 1; break; }
			}
		}
	}
	unmap_phys(run, run_pa, run_size);
	close(fd);
	if (bad) return 1;
	printf("VERIFIED: staging holds the payload (%lu bytes) and zeros beyond\n", flush_len);
	printf("FIRE go 3 0x%lx 0x%lx 0x%lx\n", image_pa, dtb_pa, flush_len);
	return 0;
}
